// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Proyecto_Final.Data;

#nullable disable

namespace Proyecto_Final.Data.Migraciones
{
    [DbContext(typeof(Contexto))]
    [Migration("20261006222622_CrearContenidoAcademicoUnidadesYMateriales")]
    partial class CrearContenidoAcademicoUnidadesYMateriales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Proyecto_Final.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoPersonal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Codigo_Personal");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Usuario_Id");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPersonal")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("Proyecto_Final.Models.AlumnoEncargado", b =>
                {
                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<int>("EncargadoId")
                        .HasColumnType("integer");

                    b.Property<int>("Parentesco")
                        .HasColumnType("integer");

                    b.HasKey("AlumnoId", "EncargadoId");

                    b.HasIndex("EncargadoId");

                    b.ToTable("AlumnoEncargados");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Archivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaveAlmacenamiento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SubidoPorUsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClaveAlmacenamiento")
                        .IsUnique();

                    b.HasIndex("SubidoPorUsuarioId");

                    b.ToTable("Archivos");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Asignacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("integer");

                    b.Property<int>("DocenteId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("GradoId")
                        .HasColumnType("integer");

                    b.Property<int>("SeccionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.HasIndex("CursoId", "GradoId");

                    b.HasIndex("SeccionId", "CursoId")
                        .IsUnique();

                    b.HasIndex("SeccionId", "GradoId");

                    b.ToTable("Asignaciones");
                });

            modelBuilder.Entity("Proyecto_Final.Models.CicloEscolar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Anio")
                        .IsUnique();

                    b.ToTable("CiclosEscolares", t =>
                        {
                            t.HasCheckConstraint("CK_CiclosEscolares_Fechas", "\"FechaInicio\" <= \"FechaFin\"");
                        });
                });

            modelBuilder.Entity("Proyecto_Final.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("GradoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GradoId", "Nombre")
                        .IsUnique();

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Carnet")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Carnet");

                    b.Property<string>("InstitucionOtorgante")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Institucion_Otorgante");

                    b.Property<string>("Nit")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("Nit");

                    b.Property<int?>("NivelAcademico")
                        .HasColumnType("integer")
                        .HasColumnName("Nivel_Academico");

                    b.Property<string>("Titulo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Titulo");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Usuario_Id");

                    b.HasKey("Id");

                    b.HasIndex("Carnet")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Encargado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Dpi")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("TelefonoAlterno")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.HasIndex("Dpi")
                        .IsUnique();

                    b.ToTable("Encargados");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Grado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nivel", "Nombre", "Carrera")
                        .IsUnique();

                    b.ToTable("Grados");
                });

            modelBuilder.Entity("Proyecto_Final.Models.HistorialTraslado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CicloEscolarId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaTraslado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InscripcionId")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RealizadoPorUsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeccionDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("SeccionOrigenId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RealizadoPorUsuarioId");

                    b.HasIndex("InscripcionId", "CicloEscolarId");

                    b.HasIndex("InscripcionId", "FechaTraslado");

                    b.HasIndex("SeccionDestinoId", "CicloEscolarId");

                    b.HasIndex("SeccionOrigenId", "CicloEscolarId");

                    b.ToTable("HistorialTraslados");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<int>("CicloEscolarId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("SeccionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeccionId");

                    b.HasIndex("AlumnoId", "CicloEscolarId")
                        .IsUnique();

                    b.HasIndex("SeccionId", "CicloEscolarId");

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArchivoId")
                        .HasColumnType("integer");

                    b.Property<bool>("Descargable")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UnidadId")
                        .HasColumnType("integer");

                    b.Property<string>("UrlExterna")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ArchivoId");

                    b.HasIndex("UnidadId", "Orden")
                        .IsUnique();

                    b.ToTable("Materiales", t =>
                        {
                            t.HasCheckConstraint("CK_Materiales_Fuente", "(\"ArchivoId\" IS NOT NULL AND \"UrlExterna\" IS NULL) OR (\"ArchivoId\" IS NULL AND \"UrlExterna\" IS NOT NULL AND LENGTH(TRIM(\"UrlExterna\")) > 0)");
                        });
                });

            modelBuilder.Entity("Proyecto_Final.Models.Periodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CicloEscolarId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CicloEscolarId", "Numero")
                        .IsUnique();

                    b.ToTable("Periodos", t =>
                        {
                            t.HasCheckConstraint("CK_Periodos_Fechas", "\"FechaInicio\" <= \"FechaFin\"");
                        });
                });

            modelBuilder.Entity("Proyecto_Final.Models.PermisoSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("PermisosSistema");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Rol", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Proyecto_Final.Models.Seccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CicloEscolarId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("GradoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("Id");

                    b.HasIndex("GradoId");

                    b.HasIndex("CicloEscolarId", "GradoId", "Nombre")
                        .IsUnique();

                    b.ToTable("Secciones");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Unidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreadoPorUsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("UnidadOrigenId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("UnidadOrigenId");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("Proyecto_Final.Models.UnidadAsignacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AsignacionId")
                        .HasColumnType("integer");

                    b.Property<string>("AsignadoPorUsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCierreAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaDisponibilidad")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int?>("PeriodoId")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoPorUsuarioId");

                    b.HasIndex("PeriodoId");

                    b.HasIndex("UnidadId");

                    b.HasIndex("AsignacionId", "Orden")
                        .IsUnique();

                    b.HasIndex("AsignacionId", "UnidadId")
                        .IsUnique();

                    b.ToTable("UnidadesAsignaciones");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<bool>("CambiarContrasena")
                        .HasColumnType("boolean")
                        .HasColumnName("Cambiar_Contrasena");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha_Creacion");

                    b.Property<DateTime?>("FechaUltimoCambioContrasena")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha_Ultimo_Cambio_Contrasena");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Primer_Apellido");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Primer_Nombre");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Segundo_Apellido");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Segundo_Nombre");

                    b.Property<string>("TercerNombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Tercer_Nombre");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_Final.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proyecto_Final.Models.Alumno", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("Proyecto_Final.Models.Alumno", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_Final.Models.AlumnoEncargado", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Alumno", "Alumno")
                        .WithMany("AlumnoEncargados")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Final.Models.Encargado", "Encargado")
                        .WithMany("AlumnoEncargados")
                        .HasForeignKey("EncargadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Encargado");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Archivo", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Usuario", "SubidoPorUsuario")
                        .WithMany()
                        .HasForeignKey("SubidoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubidoPorUsuario");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Asignacion", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Docente", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Final.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId", "GradoId")
                        .HasPrincipalKey("Id", "GradoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Final.Models.Seccion", "Seccion")
                        .WithMany()
                        .HasForeignKey("SeccionId", "GradoId")
                        .HasPrincipalKey("Id", "GradoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Docente");

                    b.Navigation("Seccion");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Curso", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Grado", "Grado")
                        .WithMany("Cursos")
                        .HasForeignKey("GradoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grado");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Docente", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("Proyecto_Final.Models.Docente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_Final.Models.HistorialTraslado", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Usuario", "RealizadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("RealizadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Final.Models.Inscripcion", "Inscripcion")
                        .WithMany()
                        .HasForeignKey("InscripcionId", "CicloEscolarId")
                        .HasPrincipalKey("Id", "CicloEscolarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Final.Models.Seccion", "SeccionDestino")
                        .WithMany()
                        .HasForeignKey("SeccionDestinoId", "CicloEscolarId")
                        .HasPrincipalKey("Id", "CicloEscolarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Final.Models.Seccion", "SeccionOrigen")
                        .WithMany()
                        .HasForeignKey("SeccionOrigenId", "CicloEscolarId")
                        .HasPrincipalKey("Id", "CicloEscolarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inscripcion");

                    b.Navigation("RealizadoPorUsuario");

                    b.Navigation("SeccionDestino");

                    b.Navigation("SeccionOrigen");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Inscripcion", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Final.Models.Seccion", "Seccion")
                        .WithMany()
                        .HasForeignKey("SeccionId", "CicloEscolarId")
                        .HasPrincipalKey("Id", "CicloEscolarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Seccion");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Material", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Archivo", "Archivo")
                        .WithMany()
                        .HasForeignKey("ArchivoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_Final.Models.Unidad", "Unidad")
                        .WithMany("Materiales")
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Archivo");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Periodo", b =>
                {
                    b.HasOne("Proyecto_Final.Models.CicloEscolar", "CicloEscolar")
                        .WithMany("Periodos")
                        .HasForeignKey("CicloEscolarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CicloEscolar");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Seccion", b =>
                {
                    b.HasOne("Proyecto_Final.Models.CicloEscolar", "CicloEscolar")
                        .WithMany("Secciones")
                        .HasForeignKey("CicloEscolarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Final.Models.Grado", "Grado")
                        .WithMany("Secciones")
                        .HasForeignKey("GradoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CicloEscolar");

                    b.Navigation("Grado");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Unidad", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Usuario", "CreadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Final.Models.Unidad", "UnidadOrigen")
                        .WithMany()
                        .HasForeignKey("UnidadOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreadoPorUsuario");

                    b.Navigation("UnidadOrigen");
                });

            modelBuilder.Entity("Proyecto_Final.Models.UnidadAsignacion", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Asignacion", "Asignacion")
                        .WithMany()
                        .HasForeignKey("AsignacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Final.Models.Usuario", "AsignadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("AsignadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_Final.Models.Periodo", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto_Final.Models.Unidad", "Unidad")
                        .WithMany("UnidadAsignaciones")
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asignacion");

                    b.Navigation("AsignadoPorUsuario");

                    b.Navigation("Periodo");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Alumno", b =>
                {
                    b.Navigation("AlumnoEncargados");
                });

            modelBuilder.Entity("Proyecto_Final.Models.CicloEscolar", b =>
                {
                    b.Navigation("Periodos");

                    b.Navigation("Secciones");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Encargado", b =>
                {
                    b.Navigation("AlumnoEncargados");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Grado", b =>
                {
                    b.Navigation("Cursos");

                    b.Navigation("Secciones");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Unidad", b =>
                {
                    b.Navigation("Materiales");

                    b.Navigation("UnidadAsignaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
